// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc2qdqoQcmSuU92arN4Si1pheFc7G6Nao',
    appId: '1:159214570801:web:cda11b18a13cb998e83410',
    messagingSenderId: '159214570801',
    projectId: 'mynote-itechsoftwares',
    authDomain: 'mynote-itechsoftwares.firebaseapp.com',
    storageBucket: 'mynote-itechsoftwares.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhhOvb86yYt1t9bzRDskHYFdX23LINHYQ',
    appId: '1:159214570801:android:9ba5e55f427702f7e83410',
    messagingSenderId: '159214570801',
    projectId: 'mynote-itechsoftwares',
    storageBucket: 'mynote-itechsoftwares.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCoudeg6c5piAE_3JWXiPNMTJCP5oR4MU',
    appId: '1:159214570801:ios:f02076d2b5ddfa07e83410',
    messagingSenderId: '159214570801',
    projectId: 'mynote-itechsoftwares',
    storageBucket: 'mynote-itechsoftwares.appspot.com',
    iosBundleId: 'tech.itechsoftwares.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCoudeg6c5piAE_3JWXiPNMTJCP5oR4MU',
    appId: '1:159214570801:ios:d4cdd230852f0546e83410',
    messagingSenderId: '159214570801',
    projectId: 'mynote-itechsoftwares',
    storageBucket: 'mynote-itechsoftwares.appspot.com',
    iosBundleId: 'tech.itechsoftwares.mynotes.RunnerTests',
  );
}
